version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_pdf_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./template.pdf:/app/template.pdf
      - ./Calibri:/app/Calibri